name: sensor_app
description: A Flutter app to show ESP32 sensor data via MQTT
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mqtt_client: any
  http: any
  fl_chart: any
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true

